version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.7-rc
    steps:
      - checkout # check out the code in the project directory
      - run: |
          python --version
          sudo apt-get install python3-pip
          pip install pipenv
          pipenv --three
          pipenv run python --version
